version: '2'
services:
  node_modules:
    build: 
     context: .
     dockerfile: Dockerfile_nodemodules
  web:
    build: .
    ports:
     - "3000:3000"
    volumes:
     - .:/starter
     - /starter/node_modules
     